const ideas=["Кинематографичный горный пейзаж на рассвете, туман и золотой свет","Роскошная альпийская долина, озеро как зеркало, ultra realistic","Футуристический город после дождя, неон и отражения","Премиальная fashion-съёмка в мягком вечернем свете","Милый 3D-персонаж в детализированном сказочном мире","Одинокий дом в горах, драматичные облака, кинематографичный кадр","Фэнтезийный лес с туманом и солнечными лучами","Минималистичный интерьер современного дома с панорамными окнами","Кинопостер для фантастического фильма","Путешественник на вершине горы, epic wide shot"];
const modes={generator:{title:"Генератор изображений",subtitle:"Создай изображение по описанию",hint:"TEXT TO IMAGE",placeholder:"Опиши изображение, которое хочешь создать...",send:"Создать",status:"FLUX · Image generation"},editor:{title:"Miya Editor",subtitle:"Редактируй изображение с помощью AI",hint:"IMAGE TO IMAGE",placeholder:"Что изменить в изображении?",send:"Применить",status:"FLUX · Image editing"},video:{title:"Видео-студия",subtitle:"Создавай видео из текста или изображения",hint:"IMAGE / TEXT TO VIDEO",placeholder:"Опиши видео или движение...",send:"Создать видео",status:"LTX · Video generation"},chat:{title:"AI Chat",subtitle:"Общайся с подключённой AI-моделью",hint:"AI CHAT",placeholder:"Напиши сообщение...",send:"Отправить",status:"AI Chat · connected models"}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let mode="generator",resultCount=1;
function toast(m){let t=$("#toast");if(!t){t=document.createElement("div");t.id="toast";document.body.appendChild(t)}t.textContent=m;t.classList.add("show");clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove("show"),2200)}
function sync(){const i=$("#composerInput");if(!i)return;i.style.height="auto";i.style.height=Math.min(130,Math.max(30,i.scrollHeight))+"px";$("#count")?.replaceChildren(document.createTextNode(i.value.length+" / 4000"))}
function empty(){if(mode==="chat"){$("#canvas").innerHTML='<div class="chat-empty"><div class="chat-logo">M</div><h3>AI Chat</h3><p>Задай вопрос, попроси написать текст или помоги себе с промптом.</p><div class="chat-suggestions"><button data-chat="Улучши мой промпт для генерации изображения">Улучшить промпт</button><button data-chat="Придумай 5 идей для изображения">Придумать идеи</button><button data-chat="Помоги создать сценарий короткого видео">Сценарий видео</button></div></div>';$$(".chat-suggestions button").forEach(b=>b.onclick=()=>{$("#composerInput").value=b.dataset.chat;sync();$("#composerInput").focus()});return}$("#canvas").innerHTML='<div class="canvas-empty"><div class="empty-symbol">✦</div><b>'+modes[mode].title+'</b><span>Здесь появится результат.</span></div><div class="canvas-grid"></div>'}
function setMode(n){mode=n;const m=modes[n];$("#modeTitle").textContent=m.title;$("#modeSubtitle").textContent=m.subtitle;$("#canvasHint").textContent=m.hint;$$("[data-mode]").forEach(x=>x.classList.toggle("active",x.dataset.mode===n));$("#composerInput").placeholder=m.placeholder;$("#composerSendText").textContent=m.send;$("#composerStatus").textContent=m.status;$("#composerOptions").style.display=n==="chat"?"none":"flex";empty();sync()}
function ideas(){const b=$("#ideas");if(!b)return;b.innerHTML="";ideas.list.sort(()=>Math.random()-.5).slice(0,5).forEach(x=>{const q=document.createElement("button");q.className="idea";q.textContent=x;q.onclick=()=>{$("#composerInput").value=x;sync()};b.appendChild(q)})}
ideas.list=ideas;
function chat(role,text){let s=$("#canvas .chat-stream");if(!s){$("#canvas").innerHTML='<div class="chat-stream"></div>';s=$("#canvas .chat-stream")}const r=document.createElement("div");r.className="chat-row "+role;r.innerHTML='<div class="chat-avatar">'+(role==="user"?"U":"M")+'</div><div class="chat-bubble"></div>';r.querySelector(".chat-bubble").textContent=text;s.appendChild(r);s.scrollTop=s.scrollHeight}
$$("[data-mode]").forEach(x=>x.onclick=()=>!x.disabled&&setMode(x.dataset.mode));
$("#composerInput").addEventListener("input",sync);$("#composerInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#composerSend").click()}});
$("#composerSend").onclick=()=>{const p=$("#composerInput").value.trim();if(!p){toast(mode==="chat"?"Напиши сообщение":"Сначала опиши, что создать");return}if(mode==="chat"){chat("user",p);$("#composerInput").value="";sync();setTimeout(()=>chat("assistant","Интерфейс AI Chat готов. Реальную модель подключим к этому composer без изменения UI."),300)}else toast(modes[mode].send+" запущено…")};
$("#composerMic").onclick=()=>toast("Голосовой ввод подключим через speech API");$("#composerAttach").onclick=()=>{$("#referenceInput")?.click();toast("Изображение выбрано как reference")};
$("#randomIdea")?.addEventListener("click",ideas);$("#clearCanvas")?.addEventListener("click",empty);$("#clearPrompt")?.addEventListener("click",()=>{$("#composerInput").value="";sync()});
$$("[data-ratio]").forEach(b=>b.onclick=()=>{select("[data-ratio]",b);$("#composerRatio").textContent=b.dataset.ratio});$$("[data-quality]").forEach(b=>b.onclick=()=>select("[data-quality]",b));$$(".model-option").forEach(b=>b.onclick=()=>{select(".model-option",b);$("#composerModel").textContent=b.dataset.model.toUpperCase()});
function select(s,e){$$(s).forEach(x=>x.classList.remove("selected"));e.classList.add("selected")}
$("#countMinus")?.addEventListener("click",()=>{resultCount=Math.max(1,resultCount-1);$("#composerCount").textContent=resultCount});$("#countPlus")?.addEventListener("click",()=>{resultCount=Math.min(4,resultCount+1);$("#composerCount").textContent=resultCount});
$$(".collapse-head").forEach(b=>b.onclick=()=>{const x=$("#"+b.dataset.target);x.classList.toggle("collapsed")});
const themeToggle=$("#themeToggle");if(localStorage.getItem("miya-theme")==="light")document.body.classList.add("light");themeToggle&&(themeToggle.textContent=document.body.classList.contains("light")?"☾":"☀",themeToggle.onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("miya-theme",document.body.classList.contains("light")?"light":"dark")});
ideas();setMode("generator");